name: takuzu-solver
version: 0.1.0.0
github: Javran/takuzu-solver
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2020 Javran Cheng"

description: A solver for https://en.wikipedia.org/wiki/Takuzu

dependencies:
- base
- containers
- terminfo
- vector

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -threaded
    - -O2

executables:
  demo:
    main: Main.hs
    source-dirs: exe
    ghc-options:
      - -main-is Main
      - -Wall
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - takuzu-solver
