resolver: lts-23.14
packages:
- fifteen-solver
- kuromasu-solver
- minesweeper-solver
- takuzu-solver
- tents-solver
- torus-solver
- arrow-solver
- kakuro-solver

extra-deps:
- pqueue-1.5.0.0
- shower-0.2.0.3
- git: https://github.com/Javran/union-find.git
  commit: 303e897af1dbea0f19906ceb054ef65bba58606c

allow-newer: true
allow-newer-deps:
- shower

notify-if-no-run-tests: false
