name: minesweeper-solver
version: 0.1.0.0
github: Javran/minesweeper-solver
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2019 Javran Cheng"

description: description

dependencies:
- base
- vector
- containers
- unordered-containers
- mtl
- dlist

library:
  source-dirs: src
  ghc-options:
    - -Wall
  

executables:
  minesweeper-demo:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - minesweeper-solver
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
