name: takuzu-solver
version: 0.1.0.0
github: Javran/puzzle-solving-collection
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2020 Javran Cheng"

description: A solver for https://en.wikipedia.org/wiki/Takuzu

dependencies:
- base
- containers
- terminfo
- vector

data-files:
  data/puzzles.txt

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - utility-ht
      - takuzu-solver
      - hspec
    ghc-options:
      - -Wall
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec

executables:
  demo:
    main: Main.hs
    source-dirs: exe
    ghc-options:
      - -main-is Main
      - -Wall
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - takuzu-solver
