name: arrow-solver
version: 0.1.0.0
github: Javran/arrow-solver
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2021 Javran Cheng"

description: description

dependencies:
- base
- containers
- monad-loops
- utility-ht
- split
- tagged

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2

executables:
  arrow-demo:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - arrow-solver
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - arrow-solver
      - QuickCheck
      - hspec
      - arithmoi
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
