name: torus-solver
version: 0.1.0.0
github: Javran/torus-solver
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2020 Javran Cheng"

description: description

ghc-options:
  - -Wall
  - -Wno-incomplete-uni-patterns
  - -Wno-x-partial

language: GHC2021

default-extensions:
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DerivingVia
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiWayIf
  - NoDoAndIfThenElse
  - NoImportQualifiedPost
  - NoNamedWildCards
  - NoUnicodeSyntax
  - OverloadedStrings
  - PartialTypeSignatures
  - TypeFamilies

dependencies:
- base
- containers
- vector
- dlist
- transformers
- split

library:
  source-dirs: src

executables:
  torus-demo:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - torus-solver
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - QuickCheck
      - torus-solver
      - hspec
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
