name: tents-solver
version: 0.1.0.0
github: Javran/tents-solver
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2020 Javran Cheng"

description: description

ghc-options:
  - -Wall
  - -Wno-incomplete-uni-patterns
  - -Wno-x-partial

language: GHC2021

default-extensions:
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DerivingVia
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiWayIf
  - NoDoAndIfThenElse
  - NoImportQualifiedPost
  - NoNamedWildCards
  - NoUnicodeSyntax
  - OverloadedStrings
  - PartialTypeSignatures
  - TypeFamilies

dependencies:
- base
- containers
- vector
- split
- strict
- terminfo
- uuid
- mtl

data-files:
  - data/puzzles.txt

library:
  generated-exposed-modules: Paths_tents_solver
  source-dirs: src

executables:
  tents-demo:
    main: Main.hs
    dependencies:
      - tents-solver
    source-dirs: exe
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - tents-solver
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
