name: fifteen-solver
version: 0.1.0.0
github: Javran/fifteen-solver
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2020 Javran Cheng"

description: description

ghc-options:
  - -Wall
  - -Wno-incomplete-uni-patterns
  - -Wno-x-partial

language: GHC2021

default-extensions:
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DerivingVia
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiWayIf
  - NoDoAndIfThenElse
  - NoImportQualifiedPost
  - NoNamedWildCards
  - NoUnicodeSyntax
  - OverloadedStrings
  - PartialTypeSignatures
  - TypeFamilies

dependencies:
- base
- containers
- unordered-containers
- vector
- split
- dlist
- hashtables
- pqueue
- transformers
- QuickCheck
- uuid
- filepath

data-files:
  - data/puzzle-bundle.txt
  - data/puzzle-bundle-moves.txt

library:
  generated-exposed-modules: Paths_fifteen_solver
  source-dirs: src

executables:
  fifteen-demo:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - fifteen-solver
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - fifteen-solver
      - hspec
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
